import { StyleSheet, Dimensions } from "react-native";
import { Theme, COLORS } from "../../utils/Theme";
const styles = StyleSheet.create({
  txtLabel: {
    color: Theme.primary,
    fontWeight: "600",
    fontSize: Theme.txtMedium,
    textAlign: "center",
  },
  txtLabel1: {
    color: Theme.primary,
    fontWeight: "400",
    fontSize: Theme.txtSmall,
    left: Theme.wp("4%"),
  },
  btnWrap: {
    backgroundColor: Theme.white,
    width: Theme.wp("40%"),
    height: Theme.hp("7%"),
    borderRadius: 10,
    elevation: 5,
    alignItems: Theme.align,
    justifyContent: Theme.align,
  },
  btnMediumWrap: {
    backgroundColor: Theme.white,
    width: Theme.width,
    height: Theme.hp("6%"),
    borderRadius: 60,

    marginTop: Theme.hp("2%"),
    alignItems: Theme.align,
    justifyContent: Theme.align,
  },
  btnEventWrap: {
    backgroundColor: Theme.white,
    width: Theme.wp("45%"),
    height: Theme.hp("7%"),
    borderRadius: 5,
    marginTop: Theme.hp("2%"),
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
  },
  btnBorder: {
    backgroundColor: Theme.secondary,
    width: Theme.width,
    height: Theme.hp("7%"),
    borderRadius: 5,
    marginTop: Theme.hp("2%"),
    alignItems: Theme.align,
    justifyContent: Theme.align,
    borderWidth: 2,
    borderColor: Theme.primary,
    paddingHorizontal: Theme.wp(2),
  },
  btnDOBWrap: {
    flexDirection: "row",
    height: Theme.hp("7%"),
    borderRadius: 5,
    borderWidth: 2,
    borderColor: Theme.lightGrey,
    marginTop: Theme.hp("2%"),
    backgroundColor: Theme.white,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Theme.wp("4%"),
  },
  txtLabelDOB: {
    color: Theme.black,
    fontSize: Theme.txtSmall,
  },
  btnSocialWrap: {
    backgroundColor: Theme.white,
    width: Theme.width,
    height: Theme.hp("7%"),
    borderRadius: 5,
    marginTop: Theme.hp("2%"),
    alignItems: Theme.align,
    justifyContent: Theme.align,
    borderWidth: 2,
    borderColor: Theme.lightGrey,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: Theme.wp("4%"),
  },
  imgLogoWrap: {
    width: Theme.wp("7%"),
    height: Theme.wp("7%"),
  },
  imgLogo: {
    width: Theme.wp("7%"),
    height: Theme.wp("7%"),
  },
  imgLogo1Wrap: {
    width: Theme.wp("37"),
    height: Theme.hp("2%"),
  },
  imgLogo1: {
    width: "100%",
    height: "100%",
  },
  txtSocial: {
    color: Theme.primary,
    fontWeight: "500",
    fontSize: Theme.txtMedium,
  },
  btnSimpleWrap: {
    backgroundColor: Theme.white,
    width: Theme.width,
    height: Theme.hp("7%"),
    borderRadius: 5,
    marginTop: Theme.hp("2%"),
    alignItems: Theme.align,
    justifyContent: Theme.align,
    borderWidth: 2,
    borderColor: Theme.lightGrey,
  },
  btnSimpleWrap1: {
    backgroundColor: Theme.white,
    width: Theme.width,
    height: Theme.hp("7%"),
    borderRadius: 5,
    marginTop: Theme.hp("2%"),
    // alignItems: Theme.align,
    justifyContent: Theme.align,
    borderWidth: 2,
    borderColor: Theme.primary,
  },
});

export default styles;
