import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFPercentage } from "react-native-responsive-fontsize";
const Theme = {
  txtTiny: RFPercentage(1.3),
  txtSmallestt: RFPercentage(1.7),
  txtSmallest: RFPercentage(1.8),
  txtSmall: RFPercentage(2),
  txtMedium: RFPercentage(2.5),
  txtLarge: RFPercentage(3),
  txtExtraLarge: RFPercentage(3.5),
  txtExtraLarge1: RFPercentage(4.5),
  align: "center",
  wp,
  hp,
  RFPercentage,
  width: wp("95%"),
  iconSizeM: RFPercentage(3.4),
  iconSizeL: 35,
  iconSizeS: 20,
  iconSizeXS: 12,
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
};
const COLORS = {
  primary: "#215675",
  secondary: "#E7873B",
  gold: "#ada11f",
  txtWhite: "#ffffff",
  txtBlue: "blue",
  lightGrey: "#E5E5E5",
  frozey: "#47B1BE",
  orange: "#F24B16",
  lightFrozey: "#CAF3F8",
  greish: "#888888",
  lightGreish: "#C4C4C4",
  green: "green",
  parrot: "#03FF3B",
  hardPurple: "#62349E",
  purple: "#431D75",
  lightPink: "#F5EEFF",
  sky: "#6BDAE6",
  yellow: "#FEF638",
  placeholderCol: "grey",
  white: "white",
  blue: "#5978ff",
  black: "black",
  txtBlack: "black",
  iconCol: "#D1D1D1",

  bold: "bold",
  errorColor: "red",
  gray1: "#525455",
};
const FONTS = {
  thin: "Metropolis-Thin",
  light: "Metropolis-Light",
  regular: "Metropolis-Regular",
  medium: "Metropolis-Medium",
  semiBold: "Metropolis-SemiBold",
  bold: "Metropolis-Bold",
  extraBold: "Metropolis-ExtraBold",
};
export { Theme, FONTS, COLORS };
